aux_loss: true
backbone: resnet50
batch_size: 1
bbox_loss_coef: 5.0
clip_max_norm: 0.1
cls_loss_coef: 2.0
coco_and_crowdhuman_prev_frame_rnd_augs: 0.2
coco_min_num_objects: 0
coco_panoptic_path: null
coco_path: data/coco_2017
coco_person_train_split: null
crowdhuman_path: data/CrowdHuman
crowdhuman_train_split: null
dataset: mot
debug: false
dec_layers: 6
dec_n_points: 4
deformable: true
device: cuda
dice_loss_coef: 1.0
dilation: false
dim_feedforward: 1024
dist_url: env://
distributed: false
dropout: 0.1
enc_layers: 6
enc_n_points: 4
eos_coef: 0.1
epochs: 100
eval_only: false
eval_train: false
focal_alpha: 0.25
focal_gamma: 5
focal_loss: false
freeze_detr: false
giou_loss_coef: 2
hidden_dim: 288
img_transform: !!python/object:argparse.Namespace
  max_size: 1333
  val_width: 800
load_mask_head_from_model: null
lr: 0.0001
lr_backbone: 1.0e-05
lr_backbone_names:
- backbone.0
lr_drop: 10
lr_linear_proj_mult: 0.05
lr_linear_proj_names:
- reference_points
- sampling_offsets
lr_track: 5.0e-05
mask_loss_coef: 1.0
masks: false
merge_frame_features: false
mot_path_train: data/BKTRIS_TRAINING
mot_path_val: data/BKTRIS_TRAINING
multi_frame_attention: true
multi_frame_attention_separate_encoder: true
multi_frame_encoding: true
nheads: 8
no_vis: false
num_feature_levels: 4
num_queries: 50
num_workers: 32
output_dir: training_results/BKTRIS_TRAINING/experiment_8_8_train_2
overflow_boxes: true
overwrite_lr_scheduler: false
overwrite_lrs: false
position_embedding: sine
pre_norm: false
resume: models/mot17_deformable_multi_frame/checkpoint_epoch_50.pth
resume_optim: false
resume_shift_neuron: false
resume_vis: false
save_model_interval: 10
seed: 64
set_cost_bbox: 5.0
set_cost_class: 2.0
set_cost_giou: 2.0
start_epoch: 1
track_attention: true
track_backprop_prev_frame: false
track_prev_frame_range: 5
track_prev_frame_rnd_augs: 0.01
track_prev_prev_frame: false
track_query_false_negative_prob: 0.4
track_query_false_positive_eos_weight: true
track_query_false_positive_prob: 0.1
tracking: true
tracking_eval: true
train_split: train_coco
two_stage: false
val_interval: 1
val_split: val_coco
vis_and_log_interval: 1
vis_port: 8097
vis_server: http://localhost
weight_decay: 5.0e-05
with_box_refine: true
world_size: 1
